# Generated by Django 3.2.2 on 2021-05-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('id_product', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('search_request', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('flat', models.CharField(max_length=255)),
                ('private_house', models.BooleanField(default=False)),
            ],
        ),
    ]
