# Generated by Django 3.2.2 on 2021-05-25 16:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionWithProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('lk', 'like'), ('fv', 'favorites'), ('bfv', 'brand_favorites'), ('or', 'order'), ('qs', 'questions'), ('rv', 'review')], max_length=5)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 16, 41, 25, 968963))),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('start_rent_date', models.DateTimeField(default=datetime.datetime(2021, 5, 25, 16, 41, 25, 969395))),
                ('end_rent_date', models.DateTimeField(blank=True)),
                ('status_rent', models.CharField(blank=True, choices=[('sms', 'one_sms_rent'), ('rent', 'daily_rent'), ('dc', 'deactivate')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_product_inside_search_request', to='maker_orders.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_user_inside_search_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewAndQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=2000)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_action_with_product_inside_review', to='maker_orders.actionwithproduct')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='search_requests',
            field=models.ManyToManyField(related_name='rn_search_request_inside_product', to='maker_orders.SearchRequest'),
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_user_inside_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('house', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=255)),
                ('delivery_method', models.CharField(max_length=255)),
                ('flat', models.CharField(blank=True, max_length=255)),
                ('private_house', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(blank=True)),
                ('qr', models.CharField(blank=True, max_length=150000)),
                ('order_status', models.CharField(blank=True, choices=[('sc', 'success'), ('or', 'ordered'), ('dl', 'delivery'), ('dld', 'delivered')], max_length=5)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_products_inside_order', to='maker_orders.product')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rn_user_inside_order', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='maker_orders.phone')),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='maker_orders.searchrequest')),
            ],
        ),
        migrations.AddField(
            model_name='actionwithproduct',
            name='phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_phone_inside_action_with_product', to='maker_orders.phone'),
        ),
        migrations.AddField(
            model_name='actionwithproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rn_product_inside_action_with_product', to='maker_orders.product'),
        ),
        migrations.AddField(
            model_name='actionwithproduct',
            name='search_request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rn_search_request_action_with_product', to='maker_orders.searchrequest'),
        ),
    ]
