# Generated by Django 3.2.2 on 2021-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker_orders', '0002_remove_order_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
