# Generated by Django 3.2.2 on 2021-05-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker_orders', '0003_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr',
            field=models.CharField(blank=True, max_length=150000),
        ),
    ]
